FROM node:20 AS build
WORKDIR /app
ARG VITE_API_BASE_URL
ARG VITE_CAMERA_STREAM_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_CAMERA_STREAM_URL=$VITE_CAMERA_STREAM_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
