image: docker:27

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - develop

  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""

  script:
    # 1. application.yml 생성
    - mkdir -p smart-factory/src/main/resources
    - |
      cat > smart-factory/src/main/resources/application.yml <<EOF
      spring:
        datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgres:5432/smart_factory
          username: postgres
          password: ${POSTGRES_PASSWORD}

        jpa:
          open-in-view: false
          hibernate:
            ddl-auto: update
          properties:
            hibernate:
              jdbc:
                time_zone: Asia/Seoul
          show-sql: false

        jackson:
          time-zone: Asia/Seoul
          mapper:
            accept-case-insensitive-enums: true

      jwt:
        secret: ${JWT_SECRET}

      mqtt:
        broker-url: tcp://mqtt:1883
      EOF

    # 2. .env 생성
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > .env
    - echo "GRAFANA_PASSWORD=$GRAFANA_PASSWORD" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env

    # 3. Gradle build
    - docker run --rm -v "$PWD/smart-factory:/app" -w /app gradle:8.7-jdk17 ./gradlew clean build -x test

    # 4. deploy
    - docker compose -f docker-compose.prod.yml down
    - docker compose -f docker-compose.prod.yml up -d --build

    # 5. 확인
    - docker ps