events {}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend:8080/;
        }

        location /camera-view/ {
            proxy_pass http://100.99.75.18:8001/camera-view/;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/;
        }
    }
}